### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by DejayRezme** [tadghh/reddit-redirect#1]
Thank you very much for this script, but after using it for a while and it worked great, then suddenly stopped working. 

Did anything change? I'm not sure how to diagnose this. I also use reddit enhancer but it worked together and even disabling reddit enhancer doesn't fix it.

I tried fiddling with the "// @match        *://www.reddit.com/*" but that didn't help. The main issue is reading notifications which pushes you back to the sh.reddit version.

**Comment by tadghh** [comment]
Oh yeah, I added a check to see if the browser had a certain cookie. I was running into issues where reddit wont let you use the old page if you arent signed in. Ill try to think of a better way.

In the mean time if you want to restore it, you should be able to roll back to an old version on greasyfork or edit this script and remove the highlighted text in the screenshot.
If you need more help feel free to ask!

![image](https://github.com/tadghh/reddit-redirect/assets/47073445/472a2f4d-6b98-4c9c-bb13-f4452440071e)

**Comment by DejayRezme** [comment]
Thank you, that fixed it!

But I didn't even have the latest version. After updating it still didn't redirect. Then removing the highlighted section fixed it. Thanks!

I really need to get more into this stuff, the older I get the more trouble I have with websites.

**Comment by tadghh** [comment]
> Thank you, that fixed it!
> 
> But I didn't even have the latest version. After updating it still didn't redirect. Then removing the highlighted section fixed it. Thanks!
> 
> I really need to get more into this stuff, the older I get the more trouble I have with websites.

Its a pretty fun skill too. If you are interested in learning the Odin Project is a very good start and it's not overwhelming either. If you have any other issues just open another posting!
